<script>
</script>

<div class="mx-12 md:mx-32 lg:mx-64 py-4 print:mx-20">
	<p class="print:hidden">A printable version is available</p>
	<h1 class="text-xl print:font-normal w-screen">
		Privacy Policy of <span class="screen:font-bold"
			>Luyx.dev, Count.bot, Treefarmer.xyz</span
		>
	</h1>
	<h1 class="text-xl w-screen mb-5 print:text-sm">
		Effective date: <span class="screen:font-bold print:text-sm"
			>08/01/2023</span
		>
	</h1>
	<ol class="list-decimal w-full print:w-screen">
		<li class="text-4xl mb-4">
			Introduction
			<ul>
				<li class="text-lg mt-4 my-3">
					Welcome to Luyx LLC. Luyx LLC (“us”, “we”, or “our”) operates
					https://luyx.dev, https://count.bot, and https://treefarmer.xyz
					(hereinafter referred to as “Services”).
				</li>
				<li class="text-lg my-3">
					Our Privacy Policy governs your visit to https://luyx.dev,
					https://count.bot, and https://treefarmer.xyz and explains how we
					collect, safeguard and disclose information that results from your use
					of our Services.
				</li>
				<li class="text-lg my-3">
					We use your data to provide and improve our Services. By using
					Servicse, you agree to the collection and use of information in
					accordance with this policy. Unless otherwise defined in this Privacy
					Policy, the terms used in this Privacy Policy have the same meanings
					as in our Terms and Conditions.
				</li>
				<li class="text-lg my-3">
					Our Terms and Conditions (“Terms”) govern all use of our Services and
					together with the Privacy Policy constitutes your agreement with us
					(“agreement”).
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4 w-full print:w-screen">
			Definitions
			<ul>
				<li class="text-lg mt-4 my-2">
					<span class="font-bold">SERVICES</span> means the https://luyx.dev website,
					the https://count.bot website, and the https://treefarmer.xyz website operated
					by Luyx LLC.
				</li>
				<li class="text-lg my-2">
					<span class="font-bold">PERSONAL DATA</span> means data about a living
					individual who can be identified from those data (or from those and other
					information either in our possession or likely to come into our possession).
				</li>
				<li class="text-lg my-2">
					<span class="font-bold">USAGE DATA</span> is data collected automatically
					either generated by the use of Service or from Service infrastructure itself
					(for example, the duration of a page visit).
				</li>
				<li class="text-lg my-2">
					<span class="font-bold">COOKIES</span> are small files stored on your device
					(computer or mobile device).
				</li>
				<li class="text-lg my-2">
					<span class="font-bold">DATA CONTROLLER</span> means a natural or legal
					person who (either alone or jointly or in common with other persons) determines
					the purposes for which and the manner in which any personal data are, or
					are to be, processed. For the purpose of this Privacy Policy, we are a
					Data Controller of your data.
				</li>
				<li class="text-lg my-2">
					<span class="font-bold">DATA PROCESSORS</span> (OR SERVICE PROVIDERS) means
					any natural or legal person who processes the data on behalf of the Data
					Controller. We may use the services of various Service Providers in order
					to process your data more effectively.
				</li>
				<li class="text-lg my-2">
					<span class="font-bold">DATA SUBJECT</span> is any living individual who
					is the subject of Personal Data.
				</li>
				<li class="text-lg my-2">
					<span class="font-bold">THE USER</span> is the individual using our Service.
					The User corresponds to the Data Subject, who is the subject of Personal
					Data.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4 w-full print:w-screen">
			Information Collection and Use
			<ul>
				<li class="text-lg mt-4">
					We collect several different types of information for various purposes
					to provide and improve our Service to you.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4 w-full print:w-screen">
			Types of Data Collected
			<ul>
				<li class="text-lg font-bold mt-4">Personal Data</li>
				<li class="text-lg mb-2">
					While using our Service, we may ask you to provide us with certain
					personally identifiable information that can be used to contact or
					identify you (“Personal Data”). Personally identifiable information
					may include, but is not limited to:
				</li>
				<ol class="list-lettered text-lg">
					<li class="my-2">Email address</li>
					<li class="my-2">First name and last name</li>
					<li class="my-2">Phone number</li>
					<li class="my-2">Address, State, Province, ZIP/Postal code, City</li>
					<li class="my-2">Cookies and Usage Data</li>
				</ol>
				<li class="text-lg font-bold mt-4">Usage Data</li>
				<li class="text-lg my-2">
					We may also collect information that your browser sends whenever you
					visit our Services or when you access our Services by or through a
					mobile device (“Usage Data”).
				</li>
				<li class="text-lg my-2">
					This Usage Data may include information such as your computer's
					Internet Protocol address (e.g. IP address), browser type, browser
					version, the pages of our Services that you visit, the time and date
					of your visit, the time spent on those pages, unique device
					identifiers and other diagnostic data.
				</li>
				<li class="text-lg my-2">
					When you access our Services with a mobile device, this Usage Data may
					include information such as the type of mobile device you use, your
					mobile device unique ID, the IP address of your mobile device, your
					mobile operating system, the type of mobile Internet browser you use,
					unique device identifiers and other diagnostic data.
				</li>
				<li class="text-lg font-bold mt-4">Tracking Cookies Data</li>
				<li class="text-lg my-2">
					We use cookies and similar tracking technologies to track the activity
					on our Services and we hold certain information.
				</li>
				<li class="text-lg my-2">
					Cookies are files with a small amount of data which may include an
					anonymous unique identifier. Cookies are sent to your browser from a
					website and stored on your device. Other tracking technologies are
					also used such as beacons, tags and scripts to collect and track
					information and to improve and analyze our Services.
				</li>
				<li class="text-lg my-2">
					You can instruct your browser to refuse all cookies or to indicate
					when a cookie is being sent. However, if you do not accept cookies,
					you may not be able to use some portions of our Services.
				</li>
				<li class="text-lg my-2">Examples of Cookies we use:</li>
				<ol class="list-lettered text-lg">
					<li class="my-2">
						<span class="font-bold">Session Cookies:</span> We use Session Cookies
						to operate our Services.
					</li>
					<li class="my-2">
						<span class="font-bold">Preference Cookies:</span> We use Preference
						Cookies to remember your preferences and various settings.
					</li>
					<li class="my-2">
						<span class="font-bold">Security Cookies:</span> We use Security Cookies
						for security purposes.
					</li>
					<li class="my-2">
						<span class="font-bold">Advertising Cookies:</span> Advertising Cookies
						are used to serve you with advertisements that may be relevant to you
						and your interests.
					</li>
				</ol>
				<li class="text-lg font-bold mt-4">Other Data</li>
				<li class="text-lg my-2">
					While using our Services, we may also collect the following
					information: sex, age, date of birth, place of birth, passport
					details, citizenship, registration at place of residence and actual
					address, telephone number (work, mobile), details of documents on
					education, qualification, professional training, employment
					agreements, non-disclosure agreements, information on bonuses and
					compensation, information on marital status, family members, social
					security (or other taxpayer identification) number, office location
					and other data.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Use of Data
			<ul>
				<li class="text-lg my-4">
					Luyx LLC uses the collected data for various purposes:
					<ol class="list-lettered text-lg">
						<li class="my-2">to provide and maintain our Service;</li>
						<li class="my-2">to notify you about changes to our Service;</li>
						<li class="my-2">
							to allow you to participate in interactive features of our Service
							when you choose to do so;
						</li>
						<li class="my-2">to provide customer support;</li>
						<li class="my-2">
							to gather analysis or valuable information so that we can improve
							our Service;
						</li>
						<li class="my-2">to monitor the usage of our Service;</li>
						<li class="my-2">
							to detect, prevent and address technical issues;
						</li>
						<li class="my-2">
							to fulfill any other purpose for which you provide it;
						</li>
						<li class="my-2">
							to carry out our obligations and enforce our rights arising from
							any contracts entered into between you and us, including for
							billing and collection;
						</li>
						<li class="my-2">
							to provide you with notices about your account and/or
							subscription, including expiration and renewal notices,
							email-instructions, etc.;
						</li>
						<li class="my-2">
							to provide you with news, special offers and general information
							about other goods, services and events which we offer that are
							similar to those that you have already purchased or enquired about
							unless you have opted not to receive such information;
						</li>
						<li class="my-2">
							in any other way we may describe when you provide the information;
						</li>
						<li class="my-2">for any other purpose with your consent.</li>
					</ol>
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Retention of Data
			<ul>
				<li class="text-lg mt-2 my-3">
					We will retain your Personal Data only for as long as is necessary for
					the purposes set out in this Privacy Policy. We will retain and use
					your Personal Data to the extent necessary to comply with our legal
					obligations (for example, if we are required to retain your data to
					comply with applicable laws), resolve disputes, and enforce our legal
					agreements and policies.
				</li>
				<li class="text-lg my-3">
					We will also retain Usage Data for internal analysis purposes. Usage
					Data is generally retained for a shorter period, except when this data
					is used to strengthen the security or to improve the functionality of
					our Service, or we are legally obligated to retain this data for
					longer time periods.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Transfer of Data
			<ul>
				<li class="text-lg mt-2 my-3">
					Your information, including Personal Data, may be transferred to – and
					maintained on – computers located outside of your state, province,
					country or other governmental jurisdiction where the data protection
					laws may differ from those of your jurisdiction.
				</li>
				<li class="text-lg my-3">
					If you are located outside United States and choose to provide
					information to us, please note that we transfer the data, including
					Personal Data, to United States and process it there.
				</li>
				<li class="text-lg my-3">
					Your consent to this Privacy Policy followed by your submission of
					such information represents your agreement to that transfer.
				</li>
				<li class="text-lg my-3">
					Luyx LLC will take all the steps reasonably necessary to ensure that
					your data is treated securely and in accordance with this Privacy
					Policy and no transfer of your Personal Data will take place to an
					organisation or a country unless there are adequate controls in place
					including the security of your data and other personal information.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Disclosure of Data
			<ul>
				<li class="text-lg mt-2 my-3">
					We may disclose personal information that we collect, or you provide:
					<ol class="list-lettered text-lg">
						<li class="my-3">
							<span class="font-bold">Disclosure for Law Enforcement.</span>
							<br />
							Under certain circumstances, we may be required to disclose your Personal
							Data if required to do so by law or in response to valid requests by
							public authorities.
						</li>
						<li class="my-3">
							<span class="font-bold">Business Transaction.</span>
							<br />
							If we or our subsidiaries are involved in a merger, acquisition or
							asset sale, your Personal Data may be transferred.
						</li>
						<li class="my-3">
							<span class="font-bold"
								>Other cases. We may disclose your information also:</span
							>
							<ol class="list-roman">
								<li class="my-2">to our subsidiaries and affiliates;</li>
								<li class="my-2">
									to contractors, service providers, and other third parties we
									use to support our business;
								</li>
								<li class="my-2">
									to fulfill the purpose for which you provide it;
								</li>
								<li class="my-2">
									for any other purpose disclosed by us when you provide the
									information;
								</li>
								<li class="my-2">with your consent in any other cases;</li>
								<li class="my-2">to our subsidiaries and affiliates;</li>
								<li class="my-2">
									if we believe disclosure is necessary or appropriate to
									protect the rights, property, or safety of the Company, our
									customers, or others.
								</li>
							</ol>
						</li>
					</ol>
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Security of Data
			<ul class="text-lg mt-2">
				The security of your data is important to us but remember that no method
				of transmission over the Internet or method of electronic storage is
				100% secure. While we strive to use commercially acceptable means to
				protect your Personal Data, we cannot guarantee its absolute security.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Your Data Protection Rights Under General Data Protection Regulation
			(GDPR)
			<ul class="text-lg mt-2 my-3">
				If you are a resident of the European Union (EU) and European Economic
				Area (EEA), you have certain data protection rights, covered by GDPR. –
				See more at https://eur-lex.europa.eu/eli/reg/2016/679/oj
			</ul>
			<ul class="text-lg my-3">
				We aim to take reasonable steps to allow you to correct, amend, delete,
				or limit the use of your Personal Data.
			</ul>
			<ul class="text-lg my-3">
				If you wish to be informed what Personal Data we hold about you and if
				you want it to be removed from our systems, please email us at
				contact@luyx.dev
			</ul>
			<ul class="text-lg my-3">
				In certain circumstances, you have the following data protection rights:
				<ol class="list-lettered">
					<li class="my-2">
						the right to access, update or to delete the information we have on
						you;
					</li>
					<li class="my-2">
						the right of rectification. You have the right to have your
						information rectified if that information is inaccurate or
						incomplete;
					</li>
					<li class="my-2">
						the right to object. You have the right to object to our processing
						of your Personal Data;
					</li>
					<li class="my-2">
						the right of restriction. You have the right to request that we
						restrict the processing of your personal information;
					</li>
					<li class="my-2">
						the right to data portability. You have the right to be provided
						with a copy of your Personal Data in a structured, machine-readable
						and commonly used format;
					</li>
					<li class="my-2">
						the right to withdraw consent. You also have the right to withdraw
						your consent at any time where we rely on your consent to process
						your personal information;
					</li>
				</ol>
			</ul>
			<ul class="text-lg">
				Please note that we may ask you to verify your identity before
				responding to such requests.
			</ul>
			<ul class="text-lg">
				Please note, we may not able to provide Service without some necessary
				data.
			</ul>
			<ul class="text-lg">
				You have the right to complain to a Data Protection Authority about our
				collection and use of your Personal Data. For more information, please
				contact your local data protection authority in the European Economic
				Area (EEA).
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Your Data Protection Rights under the California Privacy Protection Act
			(CalOPPA)
			<ul class="text-lg mt-2 my-3">
				CalOPPA is the first state law in the nation to require commercial
				websites and online services to post a privacy policy. The law’s reach
				stretches well beyond California to require a person or company in the
				United States (and conceivable the world) that operates websites
				collecting personally identifiable information from California consumers
				to post a conspicuous privacy policy on its website stating exactly the
				information being collected and those individuals with whom it is being
				shared, and to comply with this policy. – See more at:
				https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
			</ul>
			<ul class="text-lg">
				According to CalOPPA we agree to the following:
				<ol class="list-lettered">
					<li class="my-2">users can visit our site anonymously;</li>
					<li class="my-2">
						our Privacy Policy link includes the word “Privacy”, and can easily
						be found on the page specified above on the home page of our
						website;
					</li>
					<li class="my-2">
						users will be notified of any privacy policy changes on our Privacy
						Policy Page;
					</li>
					<li class="my-2">
						users are able to change their personal information by emailing us
						at contact@luyx.dev
					</li>
					<li class="my-2">
						the right to data portability. You have the right to be provided
						with a copy of your Personal Data in a structured, machine-readable
						and commonly used format;
					</li>
					<li class="my-2">
						the right to withdraw consent. You also have the right to withdraw
						your consent at any time where we rely on your consent to process
						your personal information;
					</li>
				</ol>
			</ul>
			<ul class="text-lg my-3">Our Policy on “Do Not Track” Signals:</ul>
			<ul class="text-lg mt-2">
				We currently do not recognize Do Not Track signals. Do Not Track is a
				preference you can set in your web browser to inform websites that you
				do not want to be tracked.
			</ul>
			<ul class="text-lg">
				You can enable or disable Do Not Track by visiting the Preferences or
				Settings page of your web browser.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Service Providers
			<ul class="text-lg mt-2 my-3">
				We may employ third party companies and individuals to facilitate our
				Service (“Service Providers”), provide Service on our behalf, perform
				Service-related services or assist us in analysing how our Service is
				used.
			</ul>
			<ul class="text-lg my-3">
				These third parties have access to your Personal Data only to perform
				these tasks on our behalf and are obligated not to disclose or use it
				for any other purpose.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			CI/CD tools
			<ul>
				<ul class="text-lg mt-2 my-3">
					We may use third-party Service Providers to automate the development
					process of our Service.
				</ul>
				<ul class="text-lg font-bold my-3">GitHub</ul>
				<ul class="text-lg my-3">GitHub is provided by GitHub, Inc.</ul>
				<ul class="text-lg my-3">
					GitHub is a development platform to host and review code, manage
					projects, and build software.
				</ul>
				<ul class="text-lg my-3">
					For more information on what data GitHub collects for what purpose and
					how the protection of the data is ensured, please visit GitHub Privacy
					Policy page:
					https://help.github.com/en/articles/github-privacy-statement.
				</ul>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Payments
			<ul>
				<li class="text-lg mt-2 my-3">
					We may provide paid products and/or services within Service. In that
					case, we use third-party services for payment processing (e.g. payment
					processors).
				</li>
				<li class="text-lg my-3">
					We will not store or collect your payment card details. That
					information is provided directly to our third-party payment processors
					whose use of your personal information is governed by their Privacy
					Policy. These payment processors adhere to the standards set by
					PCI-DSS as managed by the PCI Security Standards Council, which is a
					joint effort of brands like Visa, Mastercard, American Express and
					Discover. PCI-DSS requirements help ensure the secure handling of
					payment information.
				</li>
				<li class="text-lg my-3">The payment processors we work with are:</li>
				<li class="text-lg my-3">
					<span class="font-bold">PayPal:</span>
					<br />
					Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full
				</li>
				<li class="text-lg my-3">
					<span class="font-bold">Stripe:</span>
					<br />
					Their Privacy Policy can be viewed at: https://stripe.com/us/privacy
				</li>
				<li class="text-lg my-3">
					<span class="font-bold">ChargeBee:</span>
					<br />
					Their Privacy Policy can be viewed at: https://chargebee.com/privacy
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Links to Other Sites
			<ul class="text-lg">
				Our Service may contain links to other sites that are not operated by
				us. If you click a third party link, you will be directed to that third
				party's site. We strongly advise you to review the Privacy Policy of
				every site you visit.
			</ul>
			<ul class="text-lg">
				We have no control over and assume no responsibility for the content,
				privacy policies or practices of any third party sites or services.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Children's Privacy
			<ul class="text-lg mt-2 my-3">
				Our Services are not intended for use by children under the age of 13
				(“Children”).
			</ul>
			<ul class="text-lg my-3">
				We do not knowingly collect personally identifiable information from
				Children under 13. If you become aware that a Child has provided us with
				Personal Data, please contact us. If we become aware that we have
				collected Personal Data from Children without verification of parental
				consent, we take steps to remove that information from our servers.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Changes to This Privacy Policy
			<ul class="text-lg mt-2 my-3">
				We may update our Privacy Policy from time to time. We will notify you
				of any changes by posting the new Privacy Policy on this page.
			</ul>
			<ul class="text-lg my-3">
				We will let you know via email and/or a prominent notice on our Service,
				prior to the change becoming effective and update “effective date” at
				the top of this Privacy Policy.
			</ul>
			<ul class="text-lg my-3">
				You are advised to review this Privacy Policy periodically for any
				changes. Changes to this Privacy Policy are effective when they are
				posted on this page.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Contact Us
			<ul class="text-lg mt-2 my-3">
				We may update our Privacy Policy from time to time. We will notify you
				of any changes by posting the new Privacy Policy on this page.
			</ul>
			<ul class="text-lg my-3">
				If you have any questions about this Privacy Policy, please contact us:
			</ul>
			<ul class="text-lg my-3">By email: contact@luyx.dev.</ul>
		</li>
	</ol>
</div>
