<div class="mx-12 md:mx-32 lg:mx-64 py-4 print:mx-20">
	<p class="print:hidden">A printable version is available</p>
	<h1 class="text-xl print:font-normal w-screen">
		Terms of Service of <span class="screen:font-bold"
			>Luyx.dev, Count.bot, Treefarmer.xyz</span
		>
	</h1>
	<h1 class="text-xl w-screen mb-5 print:text-sm">
		Last updated: <span class="screen:font-bold print:text-sm">08/01/2023</span>
	</h1>
	<ol class="list-decimal w-full print:w-screen">
		<li class="text-4xl mb-4">
			Introduction
			<ul>
				<li class="text-lg mt-2 my-3">
					Welcome to Luyx LLC (“Company”, “us”, “we”, or “our”).
				</li>
				<li class="text-lg my-3">
					These Terms of Service (“Terms”, “Terms of Service”) govern your use
					of our web pages located at https://luyx.dev, https://count.bot, and
					https://treefarmer.xyz, and other applications, websites, or services
					operated by Luyx LLC.
				</li>
				<li class="text-lg my-3">
					Our Privacy Policy also governs your use of our Service and explains
					how we collect, safeguard and disclose information that results from
					your use of our web pages. Please read it here
					https://luyx.dev/legal/privacy.
				</li>
				<li class="text-lg my-3">
					Your agreement with us includes these Terms and our Privacy Policy
					(“Agreements”). You acknowledge that you have read and understood
					Agreements, and agree to be bound of them.
				</li>
				<li class="text-lg my-3">
					If you do not agree with (or cannot comply with) Agreements, then you
					may not use our Service. These Terms apply to all visitors, users and
					others who wish to access or use our Service.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4 w-full print:w-screen">
			Definitions
			<ul>
				<li class="text-lg mt-2 my-3">
					<span class="font-bold">SERVICE</span> means the https://luyx.dev website,
					the https://count.bot website, the https://treefarmer.xyz website, and
					any other applications, websites, and services operated by Luyx LLC.
				</li>
				<li class="text-lg my-3">
					<span class="font-bold">PERSONAL DATA</span> means data about a living
					individual who can be identified from those data (or from those and other
					information either in our possession or likely to come into our possession).
				</li>
				<li class="text-lg my-3">
					<span class="font-bold">USAGE DATA</span> is data collected automatically
					either generated by the use of Service or from Service infrastructure itself
					(for example, the duration of a page visit).
				</li>
				<li class="text-lg my-3">
					<span class="font-bold">COOKIES</span> are small files stored on your device
					(computer or mobile device).
				</li>
				<li class="text-lg my-3">
					<span class="font-bold">DATA CONTROLLER</span> means a natural or legal
					person who (either alone or jointly or in common with other persons) determines
					the purposes for which and the manner in which any personal data are, or
					are to be, processed. For the purpose of this Privacy Policy, we are a
					Data Controller of your data.
				</li>
				<li class="text-lg my-3">
					<span class="font-bold">DATA PROCESSORS</span> (OR SERVICE PROVIDERS) means
					any natural or legal person who processes the data on behalf of the Data
					Controller. We may use the services of various Service Providers in order
					to process your data more effectively.
				</li>
				<li class="text-lg my-3">
					<span class="font-bold">DATA SUBJECT</span> is any living individual who
					is the subject of Personal Data.
				</li>
				<li class="text-lg my-3">
					<span class="font-bold">THE USER</span> is the individual using our Service.
					The User corresponds to the Data Subject, who is the subject of Personal
					Data.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4 w-full print:w-screen">
			Communications
			<ul>
				<li class="text-lg mt-2 my-3">
					By creating an Account on our Service, you agree to subscribe to
					newsletters, marketing or promotional materials and other information
					we may send. However, you may opt out of receiving any, or all, of
					these communications from us by following the unsubscribe link or by
					emailing at contact@luyx.dev.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4 w-full print:w-screen">
			Purchases
			<ul>
				<li class="text-lg mt-2 my-3">
					If you wish to purchase any product or service made available through
					Service (“<span class="font-bold">Purchase</span>”), you may be asked
					to supply certain information relevant to your Purchase including,
					without limitation, your credit card number, the expiration date of
					your credit card, your billing address, and your shipping information.
				</li>
				<li class="text-lg my-3">
					You represent and warrant that: (i) you have the legal right to use
					any credit card(s) or other payment method(s) in connection with any
					Purchase; and that (ii) the information you supply to us is true,
					correct and complete.
				</li>
				<li class="text-lg my-3">
					We may employ the use of third party services for the purpose of
					facilitating payment and the completion of Purchases. By submitting
					your information, you grant us the right to provide the information to
					these third parties subject to our Privacy Policy.
				</li>
				<li class="text-lg my-3">
					We reserve the right to refuse or cancel your order at any time for
					reasons including but not limited to: product or service availability,
					errors in the description or price of the product or service, error in
					your order or other reasons.
				</li>
				<li class="text-lg my-3">
					We reserve the right to refuse or cancel your order if fraud or an
					unauthorized or illegal transaction is suspected.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Contests, Sweepstakes and Promotions
			<ul>
				<li class="text-lg mt-2 my-4">
					Any contests, sweepstakes or other promotions (collectively,
					“Promotions”) made available through Service may be governed by rules
					that are separate from these Terms of Service. If you participate in
					any Promotions, please review the applicable rules as well as our
					Privacy Policy. If the rules for a Promotion conflict with these Terms
					of Service, Promotion rules will apply.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Subscriptions
			<ul>
				<li class="text-lg mt-2 my-3">
					Some parts of Service are billed on a subscription basis
					(“Subscription(s)”). You will be billed in advance on a recurring and
					periodic basis (“Billing Cycle”). Billing cycles are set on a monthly
					basis.
				</li>
				<li class="text-lg my-3">
					At the end of each Billing Cycle, your Subscription will automatically
					renew under the exact same conditions unless you cancel it orLuyx
					LLCcancels it. You may cancel your Subscription renewal either through
					your online account management page or by contacting Luyx LLC customer
					support team.
				</li>
				<li class="text-lg my-3">
					A valid payment method, including credit card or PayPal, is required
					to process the payment for your subscription. You shall provide Luyx
					LLC with accurate and complete billing information including full
					name, address, state, zip code, telephone number, and a valid payment
					method information. By submitting such payment information, you
					automatically authorize Luyx LLC to charge all Subscription fees
					incurred through your account to any such payment instruments.
				</li>
				<li class="text-lg my-3">
					Should automatic billing fail to occur for any reason, Luyx LLC will
					terminate your Subscription and revoke all benefits included along
					with the Subscription.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Fee Changes
			<ul>
				<li class="text-lg mt-2 my-3">
					Luyx LLC, in its sole discretion and at any time, may modify
					Subscription fees for the Subscriptions. Any Subscription fee change
					will become effective at the end of the then- current Billing Cycle.
				</li>
				<li class="text-lg my-3">
					Luyx LLC will provide you with a reasonable prior notice of any change
					in Subscription fees to give you an opportunity to terminate your
					Subscription before such change becomes effective.
				</li>
				<li class="text-lg my-3">
					Your continued use of Service after Subscription fee change comes into
					effect constitutes your agreement to pay the modified Subscription fee
					amount.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Refunds
			<ul>
				<li class="text-lg mt-2 my-3">
					We issue refunds for Contracts within seven (7) days of the original
					purchase of the Contract.
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Content
			<ul class="text-lg mt-2 my-3">
				Content found on or through this Service are the property of Luyx LLC or
				used with permission. You may not distribute, modify, transmit, reuse,
				download, repost, copy, or use said Content, whether in whole or in
				part, for commercial purposes or for personal gain, without express
				advance written permission from us.
			</ul>
			<ul class="text-lg my-3">
				Luyx LLC regularly ensures that the content provided on this Website
				infringes no applicable legal provisions or third-party rights. However,
				it may not always be possible to achieve such a result. In such cases,
				without prejudice to any legal prerogatives of users to enforce their
				rights, you are kindly asked to preferably report related complaints to
				our email contained in this document.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Prohibited Uses
			<ul class="text-lg my-3 mt-2">
				You may use Service only for lawful purposes and in accordance with
				Terms. You agree not to use Service:
				<ol class="bracketed-ol">
					<li class="my-3 bracketed-li">
						In any way that violates any applicable national or international
						law or regulation.
					</li>
					<li class="my-3 bracketed-li">
						For the purpose of exploiting, harming, or attempting to exploit or
						harm minors in any way by exposing them to inappropriate content or
						otherwise.
					</li>
					<li class="my-3 bracketed-li">
						To transmit, or procure the sending of, any advertising or
						promotional material, including any “junk mail”, “chain letter,”
						“spam,” or any other similar solicitation.
					</li>
					<li class="my-3 bracketed-li">
						To impersonate or attempt to impersonate Company, a Company
						employee, another user, or any other person or entity.
					</li>
					<li class="my-3 bracketed-li">
						In any way that infringes upon the rights of others, or in any way
						is illegal, threatening, fraudulent, or harmful, or in connection
						with any unlawful, illegal, fraudulent, or harmful purpose or
						activity.
					</li>
					<li class="my-3 bracketed-li">
						To engage in any other conduct that restricts or inhibits anyone’s
						use or enjoyment of Service, or which, as determined by us, may harm
						or offend Company or users of Service or expose them to liability.
					</li>
				</ol>
			</ul>
			<ul class="text-lg my-3 mt-2">
				Additionally, you agree not to:
				<ol class="bracketed-ol">
					<li class="my-3 bracketed-li">
						Use Service in any manner that could disable, overburden, damage, or
						impair Service or interfere with any other party’s use of Service,
						including their ability to engage in real time activities through
						Service.
					</li>
					<li class="my-3 bracketed-li">
						Use any robot, spider, or other automatic device, process, or means
						to access Service for any purpose, including monitoring or copying
						any of the material on Service.
					</li>
					<li class="my-3 bracketed-li">
						Use any manual process to monitor or copy any of the material on
						Service or for any other unauthorized purpose without our prior
						written consent.
					</li>
					<li class="my-3 bracketed-li">
						Use any device, software, or routine that interferes with the proper
						working of Service.
					</li>
					<li class="my-3 bracketed-li">
						Introduce any viruses, trojan horses, worms, logic bombs, or other
						material which is malicious or technologically harmful.
					</li>
					<li class="my-3 bracketed-li">
						Attempt to gain unauthorized access to, interfere with, damage, or
						disrupt any parts of Service, the server on which Service is stored,
						or any server, computer, or database connected to Service.
					</li>
					<li class="my-3 bracketed-li">
						Attack Service via a denial-of-service attack or a distributed
						denial-of-service attack.
					</li>
					<li class="my-3 bracketed-li">
						Take any action that may damage or falsify Company rating.
					</li>
					<li class="my-3 bracketed-li">
						Otherwise attempt to interfere with the proper working of Service.
					</li>
				</ol>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			No Use By Users Under 13 Years of Age
			<ul class="text-lg mt-2 my-3">
				Service is intended only for access and use by individuals at least
				thirteen (13) years old. By accessing or using any of Company, you
				warrant and represent that you are at least thirteen (13) years of age
				and with the full authority, right, and capacity to enter into this
				agreement and abide by all of the terms and conditions of Terms. If you
				are not at least thirteen (13) years old, you are prohibited from both
				the access and usage of Service.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Accounts
			<ul class="text-lg mt-2 my-3">
				When you create an account with us, you guarantee that you are above the
				age of 18, and that the information you provide us is accurate,
				complete, and current at all times. Inaccurate, incomplete, or obsolete
				information may result in the immediate termination of your account on
				Service.
			</ul>
			<ul class="text-lg my-3">
				You are responsible for maintaining the confidentiality of your account
				and password, including but not limited to the restriction of access to
				your computer and/or account. You agree to accept responsibility for any
				and all activities or actions that occur under your account and/or
				password, whether your password is with our Service or a third-party
				service.
			</ul>
			<ul class="text-lg my-3">
				We reserve the right to refuse service, terminate accounts, remove or
				edit content, or cancel orders or subscriptions in our sole discretion.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Intellectual Property
			<ul class="text-lg mt-2 my-3">
				Service and its original content (excluding Content provided by users),
				features and functionality are and will remain the exclusive property of
				Luyx LLC and its licensors. Service is protected by copyright,
				trademark, and other laws of the United States. Our trademarks and trade
				dress may not be used in connection with any product or service without
				the prior written consent of Luyx LLC.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Error Reporting and Feedback
			<ul>
				<li class="text-lg mt-2 my-3">
					You may provide us either directly at contact@luyx.dev or via third
					party sites and tools with information and feedback concerning errors,
					suggestions for improvements, ideas, problems, complaints, and other
					matters related to our Service (“Feedback”). You acknowledge and agree
					that: (i) you shall not retain, acquire or assert any intellectual
					property right or other right, title or interest in or to the
					Feedback; (ii) Company may have development ideas similar to the
					Feedback; (iii) Feedback does not contain confidential information or
					proprietary information from you or any third party; and (iv) Company
					is not under any obligation of confidentiality with respect to the
					Feedback. In the event the transfer of the ownership to the Feedback
					is not possible due to applicable mandatory laws, you grant Company
					and its affiliates an exclusive, transferable, irrevocable,
					free-of-charge, sub-licensable, unlimited and perpetual right to use
					(including copy, modify, create derivative works, publish, distribute
					and commercialize) Feedback in any manner and for any purpose.
				</li>
				<li class="text-lg my-3">
					<span class="font-bold">Sentry:</span>
					<br />
					Sentry is open-source error tracking solution provided by Functional Software
					Inc. More information is available here: https://sentry.io/privacy/
				</li>
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Links To Other Web Sites
			<ul class="text-lg mt-2 my-3">
				Our Service may contain links to third party web sites or services that
				are not owned or controlled by Luyx LLC.
			</ul>
			<ul class="text-lg my-3">
				Luyx LLC has no control over, and assumes no responsibility for the
				content, privacy policies, or practices of any third party web sites or
				services. We do not warrant the offerings of any of these
				entities/individuals or their websites.
			</ul>
			<ul class="text-lg my-3">
				YOU ACKNOWLEDGE AND AGREE THAT LUYX LLC SHALL NOT BE RESPONSIBLE OR
				LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED
				TO BE CAUSED BY OR IN CONNECTION WITH USE OF OR RELIANCE ON ANY SUCH
				CONTENT, GOODS OR SERVICES AVAILABLE ON OR THROUGH ANY SUCH THIRD PARTY
				WEB SITES OR SERVICES.
			</ul>
			<ul class="text-lg my-3">
				WE STRONGLY ADVISE YOU TO READ THE TERMS OF SERVICE AND PRIVACY POLICIES
				OF ANY THIRD PARTY WEB SITES OR SERVICES THAT YOU VISIT.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Disclaimer Of Warranty
			<ul class="text-lg mt-2 my-3">
				THESE SERVICES ARE PROVIDED BY COMPANY ON AN “AS IS” AND “AS AVAILABLE”
				BASIS. COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND,
				EXPRESS OR IMPLIED, AS TO THE OPERATION OF THEIR SERVICES, OR THE
				INFORMATION, CONTENT OR MATERIALS INCLUDED THEREIN. YOU EXPRESSLY AGREE
				THAT YOUR USE OF THESE SERVICES, THEIR CONTENT, AND ANY SERVICES OR
				ITEMS OBTAINED FROM US IS AT YOUR SOLE RISK.
			</ul>
			<ul class="text-lg my-3">
				NEITHER COMPANY NOR ANY PERSON ASSOCIATED WITH COMPANY MAKES ANY
				WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY,
				RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE SERVICES. WITHOUT
				LIMITING THE FOREGOING, NEITHER COMPANY NOR ANYONE ASSOCIATED WITH
				COMPANY REPRESENTS OR WARRANTS THAT THE SERVICES, THEIR CONTENT, OR ANY
				SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL BE ACCURATE,
				RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED,
				THAT THE SERVICES OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF
				VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT THE SERVICES OR ANY SERVICES
				OR ITEMS OBTAINED THROUGH THE SERVICES WILL OTHERWISE MEET YOUR NEEDS OR
				EXPECTATIONS.
			</ul>
			<ul class="text-lg my-3">
				COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
				IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY
				WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR
				PARTICULAR PURPOSE.
			</ul>
			<ul class="text-lg my-3">
				THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR
				LIMITED UNDER APPLICABLE LAW.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Limitation Of Liability
			<ul class="text-lg mt-2 my-3">
				EXCEPT AS PROHIBITED BY LAW, YOU WILL HOLD US AND OUR OFFICERS,
				DIRECTORS, EMPLOYEES, AND AGENTS HARMLESS FOR ANY INDIRECT, PUNITIVE,
				SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGE, HOWEVER IT ARISES
				(INCLUDING ATTORNEYS' FEES AND ALL RELATED COSTS AND EXPENSES OF
				LITIGATION AND ARBITRATION, OR AT TRIAL OR ON APPEAL, IF ANY, WHETHER OR
				NOT LITIGATION OR ARBITRATION IS INSTITUTED), WHETHER IN AN ACTION OF
				CONTRACT, NEGLIGENCE, OR OTHER TORTIOUS ACTION, OR ARISING OUT OF OR IN
				CONNECTION WITH THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY CLAIM
				FOR PERSONAL INJURY OR PROPERTY DAMAGE, ARISING FROM THIS AGREEMENT AND
				ANY VIOLATION BY YOU OF ANY FEDERAL, STATE, OR LOCAL LAWS, STATUTES,
				RULES, OR REGULATIONS, EVEN IF COMPANY HAS BEEN PREVIOUSLY ADVISED OF
				THE POSSIBILITY OF SUCH DAMAGE. EXCEPT AS PROHIBITED BY LAW, IF THERE IS
				LIABILITY FOUND ON THE PART OF COMPANY, IT WILL BE LIMITED TO THE AMOUNT
				PAID FOR THE PRODUCTS AND/OR SERVICES, AND UNDER NO CIRCUMSTANCES WILL
				THERE BE CONSEQUENTIAL OR PUNITIVE DAMAGES. SOME STATES DO NOT ALLOW THE
				EXCLUSION OR LIMITATION OF PUNITIVE, INCIDENTAL OR CONSEQUENTIAL
				DAMAGES, SO THE PRIOR LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Termination
			<ul class="text-lg mt-2 my-3">
				We may terminate or suspend your account and bar access to Service
				immediately, without prior notice or liability, under our sole
				discretion, for any reason whatsoever and without limitation, including
				but not limited to a breach of Terms.
			</ul>
			<ul class="text-lg my-3">
				If you wish to terminate your account, you may simply discontinue using
				Service.
			</ul>
			<ul class="text-lg my-3">
				All provisions of Terms which by their nature should survive termination
				shall survive termination, including, without limitation, ownership
				provisions, warranty disclaimers, indemnity and limitations of
				liability.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Governing Law
			<ul class="text-lg mt-2 my-3">
				These Terms shall be governed and construed in accordance with the laws
				of State of Virginia without regard to its conflict of law provisions.
			</ul>
			<ul class="text-lg my-3">
				Our failure to enforce any right or provision of these Terms will not be
				considered a waiver of those rights. If any provision of these Terms is
				held to be invalid or unenforceable by a court, the remaining provisions
				of these Terms will remain in effect. These Terms constitute the entire
				agreement between us regarding our Service and supersede and replace any
				prior agreements we might have had between us regarding Service.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Changes to the Service
			<ul class="text-lg mt-2 my-3">
				We reserve the right to withdraw or amend our Service, and any service
				or material we provide via Service, in our sole discretion without
				notice. We will not be liable if for any reason all or any part of
				Service is unavailable at any time or for any period. From time to time,
				we may restrict access to some parts of Service, or the entire Service,
				to users, including registered users.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Governing Law
			<ul class="text-lg mt-2 my-3">
				We may amend Terms at any time by posting the amended terms on this
				site. It is your responsibility to review these Terms periodically.
			</ul>
			<ul class="text-lg my-3">
				Your continued use of the Platform following the posting of revised
				Terms means that you accept and agree to the changes. You are expected
				to check this page frequently so you are aware of any changes, as they
				are binding on you.
			</ul>
			<ul class="text-lg my-3">
				By continuing to access or use our Service after any revisions become
				effective, you agree to be bound by the revised terms. If you do not
				agree to the new terms, you are no longer authorized to use Service.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Waiver And Severability
			<ul class="text-lg mt-2 my-3">
				No waiver by Company of any term or condition set forth in Terms shall
				be deemed a further or continuing waiver of such term or condition or a
				waiver of any other term or condition, and any failure of Company to
				assert a right or provision under Terms shall not constitute a waiver of
				such right or provision.
			</ul>
			<ul class="text-lg my-3">
				If any provision of Terms is held by a court or other tribunal of
				competent jurisdiction to be invalid, illegal or unenforceable for any
				reason, such provision shall be eliminated or limited to the minimum
				extent such that the remaining provisions of Terms will continue in full
				force and effect.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Acknowledgement
			<ul class="text-lg mt-2 my-3">
				BY USING SERVICE OR OTHER SERVICES PROVIDED BY US, YOU ACKNOWLEDGE THAT
				YOU HAVE READ THESE TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM.
			</ul>
		</li>
		<li class="text-4xl mb-4">
			Contact Us
			<ul class="text-lg mt-2 my-3">
				Please send your feedback, comments, requests for technical support:
				<br />
				By email: contact@luyx.dev.
			</ul>
		</li>
	</ol>
</div>
